# Generated by Django 4.1.4 on 2022-12-25 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_participants',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
